version: '3.7'
services:
  tweetme-db:
    image: postgres:12.1
    volumes:
      - tweetme-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  tweetme:
    build: .
    depends_on:
      - tweetme-db
    environment:
      - DJANGO_SETTINGS_MODULE=tweetme.settings.local
    ports:
    - "8000:8000"
    volumes:
      - .:/usr/src/app/
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

volumes:
  tweetme-db-data:
